### ISSUE TITLE
Submit Sprint 1 Items in Canvas Sprint 1 assignment

### ISSUE THREAD

**Issue by k-schuler** [bnhoang2k/HorrorGame#11]

**Comment by k-schuler** [comment]
Share word document link and add teacher to manage access for project

**Comment by bnhoang2k** [comment]
@k-schuler check if you see the submission on canvas. Close this issue after.

**Comment by k-schuler** [comment]
Project 3 submission is good, but we need to list the tasks that we are going to try to get done in this sprint under the Sprint 1: 2/12 - 2/25 assignment (which is this task)

**Comment by bnhoang2k** [comment]
Just posted Sprint 1: 2/12-2/25 on canvas on what we plan to work on. Needs review then closing.
