### ISSUE TITLE
Create a list of possible resources/free assets/etc as needed in the GDD

### ISSUE THREAD

**Issue by k-schuler** [bnhoang2k/HorrorGame#16]

**Comment by bnhoang2k** [comment]
Should we have a separate file for the list? I saw an excel sheet that listed art assets that was separate from the GDD.

**Comment by k-schuler** [comment]
I would probably just put it in the GDD, either as a separate section at the bottom or spread throughout appropriately

**Comment by k-schuler** [comment]
Added possible assets to Coding Standard doc, can move it later if it fits better somewhere else
