### ISSUE TITLE
Look at ways to animate models

### ISSUE THREAD

**Issue by bnhoang2k** [bnhoang2k/HorrorGame#18]
- Rigging?
- Unity animations tutorials
- Stable Diffusion or some other software?

**Comment by bnhoang2k** [comment]
Moved here because we are still working on player controls. We're also in first person and won't need animation till enemy mobs?

**Comment by k-schuler** [comment]
Make the drawers of Desk_Describable be able to open

**Comment by bnhoang2k** [comment]
I made the drawers of desk_describable able to open. Let me know if you need anything else.
