### ISSUE TITLE
Mess with the blindness screen, add some sight at the center

### ISSUE THREAD

**Issue by k-schuler** [bnhoang2k/HorrorGame#37]
Also fix bug where it does not scale correctly to different screen sizes

**Comment by bnhoang2k** [comment]
Not actually deprecated, but put off. Features is actually very very very very very hard to implement. I asked Kathleen if I can use an asset from the store to help with this, so we're putting it off until we hear what she says.

**Comment by bnhoang2k** [comment]
she said it's ok, but will extend this into sprint 4 as well because its pretty complicated

**Comment by bnhoang2k** [comment]
currently works, but need to meet to describe what we need to do.

**Comment by k-schuler** [comment]
I don't see any difference on my end and the right side is still glitchy. I suggested last time we met to just edit the blindness image so that it isn't completely opaque in the middle and has a gradient to slightly transparent so you can see a little bit but not a lot, that is definitely doable if the complicated way using an asset doesn't pan out. Either way, this needs to be done ideally before Alpha delivery and definitely before playtesting.

**Comment by bnhoang2k** [comment]
All of it is done on the testscene. I will move the changes over to the housescene once it's more refined.
