### ISSUE TITLE
Make wire frame shader fade distance based off of arm length in Reach

### ISSUE THREAD

**Issue by k-schuler** [bnhoang2k/HorrorGame#72]

**Comment by bnhoang2k** [comment]
Can't attach it to the arm for efficiency issues, but I just hard coded the arm length into it.

**Comment by k-schuler** [comment]
Round table issue has made it clear the script is either buggy or not working. Not all the objects have the same distance fade.

**Comment by bnhoang2k** [comment]
Script is fine. Just tested it on a bunch of objects in the TestScene. Issue was that the material created weirdly and had dependencies on the wall material. I reseted it and it looks fine.

![Image](https://github.com/bnhoang2k/HorrorGame/assets/77508340/f8f8e905-9c23-4876-887d-88f188c06cc8)
