### ISSUE TITLE
Fix bug where round table legs don't have a wireframe

### ISSUE THREAD

**Issue by k-schuler** [bnhoang2k/HorrorGame#81]

**Comment by bnhoang2k** [comment]
Don't see it?

**Comment by k-schuler** [comment]
The round table on the left of the big bookcase. The legs are black and do not have a wireframe while blind.

**Comment by bnhoang2k** [comment]
it's because the wireframe distance is from the camera and the player is too tall. Not sure if this is even fixable.



![Image](https://github.com/bnhoang2k/HorrorGame/assets/77508340/3c7faae4-d9df-42c2-8726-96e727755b7d)

**Comment by k-schuler** [comment]
I went back and looked at it in the game, the whole table didn't have a wireframe and the material was set to Standard shader, reset it in game mode to Amazing Assets and looked at the distance fade, which was less than all other objects, causing its weird behavior. Outside of game mode, the tables material is different than the other materials and won't let me change the distance fade or any other wireframe settings. The distance fade is supposed to be set by a script, so it is either not working or buggy.

**Comment by bnhoang2k** [comment]
See Issue #72
