### ISSUE TITLE
Make footsteps faster

### ISSUE THREAD

**Issue by k-schuler** [bnhoang2k/HorrorGame#85]
Footsteps often don't make noise if the player doesn't move enough

**Comment by bnhoang2k** [comment]
Made it faster, but don't know how fast you want the footsteps to be.


![Image](https://github.com/bnhoang2k/HorrorGame/assets/77508340/f37c7de3-6388-4e46-ba05-00262abec791)

to adjust, go to firstpersoncontroller within playerCapsule and lower the value as needed.
