### ISSUE TITLE
Create title screen

### ISSUE THREAD

**Issue by bnhoang2k** [bnhoang2k/HorrorGame#87]
I have ideas for this, but won't have time before friday to get this done.

**Comment by k-schuler** [comment]
This is the same as my splash screen task, but if you want to handle it go for it.

**Comment by bnhoang2k** [comment]
I was thinking title screen with play button, to go into splash screen with instruction?

**Comment by k-schuler** [comment]
I was thinking it would just be one screen

**Comment by k-schuler** [comment]
I had some time so I went ahead and made the instruction/title screen
